language: java
jdk:
  - openjdk11

script:
  - mvn clean test
after_success:
  - bash <(curl -s https://codecov.io/bash) -t a408e7b6-8bc0-4b9f-a40c-46a682cf5c9e

notifications:
  email:
    recipients:
      - afraccaro@fi.uba.ar
      - aschmidt@fi.uba.ar
      - ccaserta@fi.uba.ar
      - sczop@fi.uba.ar
      - kgadacz@fi.uba.ar
    on_failure: always
